### PR TITLE
Fix Strings translation in two PHP files

### PR DESCRIPTION
**Pull request by DAnn2012**
Fix Strings translation in two PHP files

### CODE REVIEW

**Comment by YMC-22** [comment]
Thanks

**Comment by DAnn2012** [comment]
Hello @YMC-22 

Thank you for the reply.

However, I see that the [changes to the advanced.php](https://github.com/YMC-22/smart-filter/pull/21/commits/429f321a9791860751dd6f7ebc010ddbca1306d7) file were not included in the new version 2.8.32.

Why?

Thank you.

**Comment by YMC-22** [comment]
We will take this into account in future releases of the plugin. Thanks for your support in the development of our plugin.

**Comment by DAnn2012** [comment]
Hello @YMC-22

Please could you take a look at this PR of mine?

Thanks.

**Pull request closed without merging**
